[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "torch>=2.0",   # BuildExtension lives inside torch
    "triton",
    "ninja",        # optional, speeds up CUDA compilation
    "numpy"
]
build-backend = "setuptools.build_meta"
