[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja",        # optional, speeds up CUDA compilation
    "torch>=2.7",   # BuildExtension lives inside torch
    "triton>=3.3.0",
    "numpy>=1.26.4",
]
build-backend = "setuptools.build_meta"
